project:
  name: quickstart-ct-clickstream-analytics
  owner: quickstart-eng@amazon.com
  regions:
    - ap-northeast-1
    - ap-northeast-2
    - ap-south-1
    - ap-southeast-1
    - ap-southeast-2
    - eu-central-1
    - eu-north-1
    - eu-west-1
    - eu-west-2
    - eu-west-3
    - sa-east-1
    - us-east-1
    - us-west-1
    - us-east-2
    - us-west-2
    - ca-central-1
  s3_bucket: ''
  parameters:
    AvailabilityZones: "$[taskcat_genaz_2]"
    VPCCIDR: 10.0.0.0/16
    PrivateSubnet1CIDR: 10.0.0.0/19
    PrivateSubnet2CIDR: 10.0.32.0/19
    PublicSubnet1CIDR: 10.0.128.0/20
    PublicSubnet2CIDR: 10.0.144.0/20
    KeyPairName: "$[taskcat_getkeypair]"
    RemoteAccessCIDR:  "10.0.0.0/16"
    AppKeyPairName: "$[taskcat_getkeypair]"
    OperatorEMail: override
    ESDomainName: "$[taskcat_random-string]"
    ESIndex: "taskcat"
    ESType: "doc"
    DatabaseName: "dev"
    MasterUserPassword: "$[taskcat_genpass_8A]"
    RedshiftColumns: ""
    WebsiteContent: ""
    QSS3BucketName: "$[taskcat_autobucket]"
    QSS3BucketRegion: "$[taskcat_current_region]"

tests:
  default:
    template: ./templates/quickstart-ct-clickstream-analytics-master.template.yaml
    regions:
      - us-west-2
    s3_bucket: ''